[package]
name = "spam_or_ham"
version = "0.1.0"
authors = ["James DeVore <jdevore4592@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.8.3"
zip = "0.5.4"
rustlearn = "0.4.0"
time = "0.2.5"